### PR TITLE
Docker-based dev setup

### PR DESCRIPTION
**Pull request by MrSnyder**
This PR solves #18: It contains the necessary changes to get a docker-based dev setup running.

Starting the docker environment:
```bash
cd mrmap/docker
docker-compose -f docker-compose-dev.yml up --build
```

The command above will start containers for the following services:
* PostgresSQL 11 (with PostGIS)
* Redis 6.2
* MapServer 7.6
* Nginx 1.19 (proxying access to the host's Django development server)

Starting the django development server for the docker environment:
```bash
DJANGO_SETTINGS_MODULE=MrMap.settings_docker python mrmap/manage.py runserver 0.0.0.0:8000
```

The command above will start a Django development server with configuration for the docker environment.

### CODE REVIEW

**Comment by simonseyock** [comment]
the following commands should be run the first time, after `docker-compose up`:
```
python manage.py migrate
python manage.py setup
```

**Comment by simonseyock** [comment]
Through the nginx server the application is reachable under port 80 and 443 on localhost.

**Comment by simonseyock** [comment]
also docker v20 or greater and docker-compose v1.28 or greater is needed

**Comment by jokiefer** [comment]
@MrSnyder @simonseyock 
pls [grant rights](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for maintainers on this pr. Otherwise can't edit your branch.

**Comment by MrSnyder** [comment]
Thanks for the link, I wasn't aware of this GitHub feature.

However, I didn't uncheck "Allow edits from maintainers." when creating the PR... and cannot find the option when editing the PR. Still, I assume pushing to the feature branch doesn't work for you at the moment?

**Comment by MrSnyder** [comment]
We just found that one needs to specifiy the DJANGO_SETTINGS_MODULE in order to start Celery worker/beat for the docker-based setup as well:

```bash
DJANGO_SETTINGS_MODULE=MrMap.settings_docker celery -A MrMap worker -l INFO
DJANGO_SETTINGS_MODULE=MrMap.settings_docker celery -A MrMap beat -l INFO
```

BTW, we introduced the usage of DJANGO_SETTINGS_MODULE to allow different environments without changing files manually. Does this work for you and should we have a short discussion about this approach?

**Comment by jokiefer** [comment]
Yeah this works for me and i have already written docs for this. But at the moment i can't push it to your branch from fork or edit it in this PR.

**Comment by jokiefer** [comment]
maybe come up for a short session on https://meet.jit.si/gdirp

**Pull request merged**
